all:
  hosts:
    statice:
      ansible_host: 185.207.106.73
      ip: 185.207.106.73
      access_ip: 10.10.10.195
    protea:
      ansible_host: 185.194.141.245
      ip: 185.194.141.245
      access_ip: 10.10.10.118
    datura:
      ansible_host: 185.194.141.246
      ip: 185.194.141.246
      access_ip: 10.10.10.147
  children:
    kube-master:
      hosts:
        statice:
        protea:
        datura:
    kube-node:
      hosts:
        statice:
        protea:
        datura:
    etcd:
      hosts:
        statice:
        protea:
        datura:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
